### ISSUE TITLE
Mikio Plugin breaks Struct Plugin Aggregation

### ISSUE THREAD

**Issue by eFreshman** [nomadjimbob/mikioplugin#13]
I'm switching to a non-Bootstrap-based template and wanted to replace some elements of the Bootstrap Wrapper plugin with the Mikio plugin in order to use them with the sprintdoc template.

Unfortunately, I am now realizing that I am not getting an aggregation of structured data (struct table). If I deactivate the Mikio plugin, I immediately get the struct table correctly displayed again.

Can someone reproduce the problem?

**Comment by nomadjimbob** [comment]
Thanks for letting me know. Before I take a look at what is going on, just want to confirm this is using the struct:aggregation plugin here https://www.dokuwiki.org/plugin:struct:aggregation ?

**Comment by eFreshman** [comment]
> Thanks for letting me know. Before I take a look at what is going on, just want to confirm this is using the struct:aggregation plugin here https://www.dokuwiki.org/plugin:struct:aggregation ?

Yes that's right.
It's about the plugin struct https://www.dokuwiki.org/plugin:struct and the aggregation syntax to be used.
Thanks for taking care of it.

**Comment by nomadjimbob** [comment]
A simple temporary fix is to comment out line 22 in `/lib/plugins/mikioplugin/syntax/hr.php` which is causing the conflict.

This would change:
```php
    public function connectTo($mode)
    {
        $this->Lexer->addSpecialPattern('----', $mode, 'plugin_mikioplugin_' . $this->getPluginComponent());
        parent::connectTo($mode);
    }
```

to:

```php
    public function connectTo($mode)
    {
        //$this->Lexer->addSpecialPattern('----', $mode, 'plugin_mikioplugin_' . $this->getPluginComponent());
        parent::connectTo($mode);
    }
```

then clear the affected page caches by making a slight change to the page content, then reverting it forcing dokuwiki to re-render the page.

This will also disable the horizontal line syntax in `----` MikioPlugin for the time being.

I will try to get a real fix and update over the next few days

**Comment by nomadjimbob** [comment]
Fixed in latest release (2021-12-13)
