### ISSUE TITLE
Table rendering in accordion

### ISSUE THREAD

**Issue by Melphios** [nomadjimbob/mikioplugin#15]
Hi,

First thanks for all the work that you do for this plugins :) and happy new year ;) !

I've met an issue when trying to put a table inside an accordion, maybe my syntax is bad .

`<accordion autoclose>
<accordion-item title="test">
^ A  ^ B  ^
| C  | D  |
</accordion-item>
</accordion>`

Result in
![Screenshot_20220108_105441](https://user-images.githubusercontent.com/88441373/148639951-dae5e702-e046-4d93-ad63-7c45ba181d8d.png)

Thanks for your help :)

**Comment by nomadjimbob** [comment]
Thanks for letting me know. This has been fixed in the latest release
