### ISSUE TITLE
Cards bg colour issues when used with mikio dark mode

### ISSUE THREAD

**Issue by chrbinder** [nomadjimbob/mikioplugin#16]
Hi, I love the new dark mode of the mikio theme and the customizations that are possible!
I'm making extensive use of the mikioplugin cards on my site. I've noticed that when using them together with dark mode, the cards stay white and their text appears . Apparently, the style is set in /lib/plugins/mikioplugin/css.php.

Is there a way to change the background colour of cards or can it simply be inverted?
Thanks for your help! 😄

**Comment by nomadjimbob** [comment]
Thanks for the kind words. As you have found, the plugin is not yet updated to support dark-mode themes, nor does it use the Mikio style settings that users can change in the admin area (this was to allow it to remain independent of the theme).

The next update for the plugin will use the styling from the Mikio theme if it is present and active. This will then allow a constant color theme across both the theme and plugin and prevent users from needing to update styling information in 2 different locations.

However, this does require a few code changes and some additions to the Mikio theme. I am hoping to have this in the next week or two.
