### ISSUE TITLE
No dropdown support

### ISSUE THREAD

**Issue by armandostyl** [nomadjimbob/mikioplugin#18]
Unless I'm missing something, there is no support for dropdown navigation menus.

As I am completely clueless as to how to begin to implement that, any tips or roadmap for implementation?

Thank you, and thanks for the awesome plugin and template!

**Comment by nomadjimbob** [comment]
You can enable the dokuwiki navigation menu to be dropdown in admin > configuration settings with the `tpl»mikio»navbarDWMenuCombine` setting.

Dokuwiki does not support custom items in the navbar directly and it is not a feature in the mikio template nor the plugin. It isn't a feature I needed and you are the first to request it.

It will take me a week or 2 to add this feature into the template and plugin.

**Comment by armandostyl** [comment]
I was trying to move away from the bootstrap3 wrapper and to the mikio plugin and template, and use dropdown menus in the sidebar as I did in the previous iteration.

Is there anything I can do to help? Or at the very least, buy you a beer?

**Comment by armandostyl** [comment]
Here is the link to Lotar's page with the [example](https://www.lotar.altervista.org/wiki/wiki/plugin/bootswrapper/nav).

And here is the [repository](https://github.com/search?q=repo%3Agiterlizzi%2Fdokuwiki-plugin-bootswrapper%20nav&type=code).

**Comment by armandostyl** [comment]
![image](https://github.com/nomadjimbob/mikioplugin/assets/112349119/6494a3d7-842a-456a-ab0b-50064b8cf274)
This is what I'm trying to replicate in mikio.

**Comment by nomadjimbob** [comment]
I've added a `nav` element that can create downdown in the latest release of the plugin. The [wiki has been updated](https://github.com/nomadjimbob/mikioplugin/wiki/Nav) to show its usage.
