### ISSUE TITLE
Listgroup and bold

### ISSUE THREAD

**Issue by armandostyl** [nomadjimbob/mikioplugin#20]
Hi again.

When I make a portion of the text in an item from a listgroup, the text misbehaves. The bold part is aligned left, and the regular part is aligned right.

See image attached.
![Screenshot from 2023-06-15 20-19-03](https://github.com/nomadjimbob/mikioplugin/assets/112349119/fdb63277-a93f-4503-8e68-0f389b068b24)

**Comment by nomadjimbob** [comment]
Fixed in the latest release. Thank you for reporting the issue.
