### ISSUE TITLE
Conflicting small tag

### ISSUE THREAD

**Issue by Rayaqu** [nomadjimbob/mikioplugin#22]
Hi. Thank you for making Mikio plugin, I find its use really helpful to organize my documents. However, I have been conflicted with a different plugin that implements HTML tags, specifically with the ``<small>`` tag. I intended to use this tag in a inline text, but Mikio plugin overrides this and forces the text in a new line. So in an attempt to personalize this, I found out that there are extra tags that aren't yet documented. In a quick look, apart from ``<small>``, there's also ``<text>`` and ``<br>`` tags and I am liking the addition.

Is it possible to make ``<small>`` tag to optionally function as inline text?. As a workaround I was thinking in removing/renaming the ``small.php`` file, but will it break other Mikio plugin functions?

**Comment by nomadjimbob** [comment]
Thanks for the comments. The small, text and br tags were added a while ago, I've just forgotten to update the docs. Sorry.

I will fix the small tag as it should be inline. In the meantime, you can update the file to:

```php
class syntax_plugin_mikioplugin_small extends syntax_plugin_mikioplugin_core {
    public $tag                 = 'small';
    public $hasEndTag           = true;

    public function getPType() { return 'normal'; }
    
    public function render_lexer_enter(Doku_Renderer $renderer, $data) {
        $renderer->doc .= '<small class="' . $this->elemClass . ' ' . $this->classPrefix . 'small">';
    }


    public function render_lexer_exit(Doku_Renderer $renderer, $data) {
        $renderer->doc .= '</small>'; 
    }
}
```


The line `public function getPType() { return 'normal'; }` will make the tag inline (you may need to re-save the affected pages due to caching).


You can remove any of the files (except `core.php`) from inside the syntax folder and it _shouldn't_ cause any issues.

### Todo
- [ ] Updated Documentation to include `<small>`, `<text>`, `<br>` tags
- [ ] Updated `small` syntax to be inline

**Comment by nomadjimbob** [comment]
Fixed in the 2023-09-11 release. Added a [new option](https://github.com/nomadjimbob/mikioplugin/tree/2023-09-11#disabling-tags) file to disable individual tags in the plugin if found to be conflicting with other plugins or just don't want them to be available to users.

**Comment by Rayaqu** [comment]
Thanks for updating so quicky!
So I updated the plugin and I was testing it and I get this error anywhere mikio plugin is used:
![image](https://github.com/nomadjimbob/mikioplugin/assets/126368952/a658c4e1-1e54-48ed-9ad9-c84a21553af2)

I disabled other plugins to test and it seems that ``<small>`` tag in Mikio Plugin does not render the contents. Also to test disabling functions in ``disabled-tags.php``, I disabled ``<button>`` and ``<button-group>`` and they were still rendering xD

**Comment by nomadjimbob** [comment]
I have fixed the problem. There was a bug in my code and it appears that Dokuwiki does not call the disable code in some cases, so I've rewritten it and tested it.

Should be no problems now (hopefully)
