### ISSUE TITLE
Pagenation highlight and next/prev not working

### ISSUE THREAD

**Issue by armandostyl** [nomadjimbob/mikioplugin#26]
Pagenation doesn't seem to be working (highlighting **or** next/prev functions).
Perhaps it doesn't work with nice urls?

**Comment by nomadjimbob** [comment]
Thanks for reporting this. Can confirm that the pagination breaks with nice urls set (and that it is spelt incorrectly). I'll fix this asap.

**Comment by nomadjimbob** [comment]
Thanks for letting me know. A fix was applied to that a few minutes ago. I've reopened the issue for now just so it stays in my todo list to check again before todays update release

**Comment by nomadjimbob** [comment]
Need to update the code to accomodate the following condition:

- [ ] The following pathnames are treated as different when they are the same to the end user `/doku.php` => `/doku.php/start` or `/doku.php?id=start`. End slashes are also optional

**Comment by WetenSchaap** [comment]
The Prev/next buttons are working now, thanks! 

However, pagination now looks different then before I applied the update. Before it looked like it does in the wiki (but without the current page highlighted. After the update it looks like this:

![image](https://github.com/nomadjimbob/mikioplugin/assets/36634689/c975b092-3c98-4719-937e-58e6bfebdb5c)

**Comment by nomadjimbob** [comment]
Fixed a bug with the LESS code which may be causing what you are seeing. You may need to refresh your browser cache as well. Let me know how it goes

**Comment by WetenSchaap** [comment]
Perfect thanks for the quick action!

![image](https://github.com/nomadjimbob/mikioplugin/assets/36634689/e2805fac-19eb-40a6-9ebb-8f5ed3a23ce6)
