### ISSUE TITLE
plugin breaks struct table display

### ISSUE THREAD

**Issue by stevesong** [nomadjimbob/mikioplugin#3]
The plugin appears to disable the interpretation of a struct table display command of the form:

```
---- struct global ----
schema: myschema
----

```
I thought the problem was with your theme but have isolated it to the plugin

**Comment by nomadjimbob** [comment]
Commenting out lines 18-21 in syntax/hr.php seems to fix the issue.

I will remove the quad dash to the horizontal line element (it can be created with <hr> anyway) in the initial release in the next few days. There are also some cosmetic table styling issues on the schema admin pages that need to be fixed before that release.

**Comment by nomadjimbob** [comment]
HR conflict is fixed in current release
