### ISSUE TITLE
mikioplugin doesn't seem to be active

### ISSUE THREAD

**Issue by dwightmulcahy** [nomadjimbob/mikioplugin#31]
I installed the mikioplugin via the dokuwiki extension manager.  I created a very simple page that contained the following:

```
<alert dark align-left width=20em>This is a dark alert aligned left</alert>
<alert dark align-center width=20em>This is a dark alert aligned center</alert>
<alert dark align-right width=20em>This is a dark alert aligned right</alert>
```

When I view the page, it looks like this (obviously not working):
```
This is a dark alert aligned left
This is a dark alert aligned center
This is a dark alert aligned right
```

I've tried logging out and in again with the same results.  I've disabled all the other extensions I had installed (not many).  I've looked through the logs and found nothing related to mikioplugin.

I've looked through the docs and couldn't find anything I was missing/doing wrong.  Any suggestions?

**Comment by nomadjimbob** [comment]
Not really sorry, maybe delete the Mikio plugin extension and reinstal it.

I just your code on a new install of Dokuwiki using the latest Stable and Development Snapshots, installing Mikio plugin through the extension manager. I tried it in PHP versions 7.4.33, 8.1.17, 8.2.4.

I would need to know the version of DokuWiki, PHP and any log files (PHP log file and Dokuwiki logs at /data/log/*) that may help (these can be emailed to me james.collins [at] outlook.com.au) to track it down in your case.

**Comment by dwightmulcahy** [comment]
So, I resolved the issue by installing the `Mikio theme template`... 

thanks for the quick reply!
