### ISSUE TITLE
Is there a way to avoid having the images stretched to the maximum in cards?

### ISSUE THREAD

**Issue by Elanndelh** [nomadjimbob/mikioplugin#32]
Hello ! 
First of all: thank you for this superb plugin, it gives a more modern look to wikis, it's very pleasant. However, I'm having a little trouble getting it to work properly.

### My problem
I want to add icons or smileys to cards, but the image restriction settings are not taken into account. This results in a weird effect like the image below.
![uII3mJaLvG](https://github.com/nomadjimbob/mikioplugin/assets/80389410/2cfe73ac-a860-445b-931d-b88abcb01cf4)

Code : 
```
<row>
<col 8><card primary>{{image.png?16x16}}</card></col>
<col 4>
<row><card secondary>:-X</card></row>
<row><card danger>Small card</card></row>
<row><col><card success>XS card</card></col><col><card warning>XS card</card></col> <col><card info>XS card</card></col> </row>
</col>
</row>
```

### My request
Is there a way to avoid this stretch?

**Comment by nomadjimbob** [comment]
There is no easy way to prevent this, but I will fix this in the next release.

For the time being, it can be overridden in the `/lib/plugins/mikioplugin/assets/styles.less` file by commenting out the `.img` around line 903 (see image of it commented out).

You may need to refresh your [DokuWiki cache](https://www.dokuwiki.org/caching).

<img width="451" alt="Screenshot 2024-03-03 at 9 33 11 pm" src="https://github.com/nomadjimbob/mikioplugin/assets/26953208/5d19e726-4c93-4e66-a834-af9973a5cecb">
