### ISSUE TITLE
Is this plugin open for testing yet?

### ISSUE THREAD

**Issue by GJRobert** [nomadjimbob/mikioplugin#4]
Pardon me, since I saw this plugin mentioned on the mikio template main page on DokuWiki.org:
```
The Mikio Plugin is also available to add bootstrap 4 style + more elements to DokuWiki pages.
```
It seems that this plugin provides new syntax for bootstrap elements.
Is there any hint or cheatsheet to know the syntax in the inventory?

Thanks!

**Comment by nomadjimbob** [comment]
Sorry, I have created a release and working through the [wiki](https://github.com/nomadjimbob/mikioplugin/wiki) now that contains the DokuWiki codes.

There are still some smaller issues, so please report any issues you come across, Thanks!

I will close this issue once I have completed updating the [wiki](https://github.com/nomadjimbob/mikioplugin/wiki).

**Comment by GJRobert** [comment]
Please have my bow of appreciation
![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Japan_-_Tokyo_%289980668875%29.jpg/320px-Japan_-_Tokyo_%289980668875%29.jpg)
