### ISSUE TITLE
Is there a way to add additional styles? 

### ISSUE THREAD

**Issue by witchka** [nomadjimbob/mikioplugin#6]
Hi! I love the plugin, it works very smoothly, but I was wondering if it's possible to add your own custom style(s) to use with the various elements? I know you can customise them as I tried that and it worked fine, but there are a few parts of my wiki that would be best off with their own style. 

I tried adding this to the LESS file (in the appropriate places with the other code like this): 

// Accent
@accent-btn-text-color:                       #fff;
@accent-btn-bg-color:                         #6d2585;
@accent-btn-border-color:                     #91679e;
@accent-btn-hover-text-color:                 #ffffff;
@accent-btn-hover-bg-color:                   #c499d1;
@accent-btn-hover-border-color:               #63416e;
@accent-alert-text-color:                     #ffffff;
@accent-alert-bg-color:                       #91679e;
@accent-alert-border-color:                   #63416e;

// Accent Outline
@outline-accent-btn-text-color:               #91679e;
@outline-accent-btn-bg-color:                 transparent;
@outline-accent-btn-border-color:             #91679e;
@outline-accent-btn-hover-text-color:         #fff;
@outline-accent-btn-hover-bg-color:           #c499d1;
@outline-accent-btn-hover-border-color:       #63416e;

and 

    &.mikiop-type-accent { ._mikiop-btn-type("accent"); }
    &.mikiop-type-outline-accent { ._mikiop-btn-type("outline-accent"); }

but using "accent" as a style just gives you plain styling no matter what whacky colours you change it too. I was wondering if I was missing something or if this was just an impractical idea?

Thank you for your time.

**Comment by nomadjimbob** [comment]
It should work and if it doesn't, I don't see why I can't find a way to have this as an option. Let me look into it more...

**Comment by nomadjimbob** [comment]
Apologies, I misunderstood your initial request. This option is now supported in the latest release as well as custom stylesheets. Sorry it took me so long to get around to this.

This can be now done by adding the variables:

```
// Accent
@accent-btn-text-color: #fff;
@accent-btn-bg-color: #6d2585;
@accent-btn-border-color: #91679e;
@accent-btn-hover-text-color: #ffffff;
@accent-btn-hover-bg-color: #c499d1;
@accent-btn-hover-border-color: #63416e;
@accent-alert-text-color: #ffffff;
@accent-alert-bg-color: #91679e;
@accent-alert-border-color: #63416e;
```

in a file named `/styles/variables.less` (all variables are required to be defined)

then define the style using `._mikiop-custom-type(accent)` in a file named `/styles/style.less`.

You can now use the new style on your wiki as `<alert accent>My alert</alert>`.


You can read more on the [Customising page within the Wiki](https://github.com/nomadjimbob/mikioplugin/wiki/Customising).
