### ISSUE TITLE
Rendering tables inside <card> element

### ISSUE THREAD

**Issue by anthyeung** [nomadjimbob/mikioplugin#7]
First of all, thanks for all your work on this modern and robust plugin! I'm not sure if I'm not implementing this plugin correctly, but I can't seem to render a table or a list within a `<card>` element

**Steps to reproduce error:**
Table:
```
<card header="Featured" footer="Footer info" title="Special title treatment" text-center>
^ A  ^ B  ^
| C  | D  |
</card>
```
List:
```
<card header="Header">
  * Item 1
  * Item 2
</card>
```

What ends up happening is the card is rendered correctly, but the table and list is outputted as plain text. Any thoughts on how I can force proper rendering within the card?

**Comment by nomadjimbob** [comment]
Sorry it took me some time to get onto this. It look likes I have fixed the rendering problem in the latest release 2021-03-02
